# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Initial Setup
on:
  push:
    branches: [ "chart_widget" ]
  pull_request:
    branches: [ "chart_widget" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@kumabha-bh'
    - name: Use .npmrc
      uses: bduff9/use-npmrc@v1.2
      with:
        dot-npmrc: ${{ secrets.DOT_NPMRC }}
    - name: Re-write
      run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN  }}' > ${{ github.workspace }}/.npmrc    
    - name: NPM Install
      run: npm i --legacy-peer-deps